stages:          # List of stages for jobs, and their order of execution
  - inProgress
  - mergeRequest

variables:
  LANG: "en_US.UTF-8"
  LC_ALL: "en_US.UTF-8"

build-job:    
    rules:
        - if: '$CI_COMMIT_BRANCH =~ /(APP|KTO|SP)-[0-9]+/'
        - if: '$CI_PIPELINE_SOURCE != "merge_request_event"'
    stage: inProgress 
    script:              
      - EMAIL_NAME="$(echo $GITLAB_USER_EMAIL | sed "s/@.*//")"
      - >
        curl --request POST --url "https://jira.higgstar.com/rest/api/2/issue/${CI_COMMIT_BRANCH}/transitions" --data '{"transition":{"id":"'${JIRA_ISSUE_START_WORKING_ACTION}'"}}' --header "Authorization: Bearer $JIRA_TOKEN" --header "Content-Type: application/json"
      - >
        curl --request POST --url "https://jira.higgstar.com/rest/api/2/issue/${CI_COMMIT_BRANCH}/transitions" --data '{"transition":{"id":"'${JIRA_ISSUE_SUBTASK_START_WORKING_ACTION}'"}}' --header "Authorization: Bearer $JIRA_TOKEN" --header "Content-Type: application/json"
      - >
        JIRA_SUB=$(curl --request PUT --url "https://jira.higgstar.com/rest/api/2/issue/$CI_COMMIT_BRANCH/assignee" --data "{\"name\":\"$EMAIL_NAME\"}" --header "Authorization: Bearer $JIRA_TOKEN" --header "Content-Type: application/json")
      - echo -e "$JIRA_SUB"

merge-job:      
    before_script:            
        - source ~/.nvm/nvm.sh
        # - nvm install node
        # - npm install -g @commitlint/cli @commitlint/config-conventional
        # - echo 'module.exports = {extends:["@commitlint/config-conventional"]}' > commitlint.config.js
        - curl https://gitlab.higgstar.com/api/v4/projects/695/repository/files/commitlint-gitlab.sh/raw | bash
    rules:
        - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
        - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    stage: mergeRequest
    variables:
        # CI_DEBUG_TRACE: "true"
        MR_COMMAND : 'curl --header PRIVATE-TOKEN:$GITLAB_AUTH_TOKEN https://gitlab.higgstar.com/api/v4/projects/${CI_PROJECT_ID}/merge_requests/${CI_MERGE_REQUEST_IID}'
        BRANCH_PATTERN : '(APP|KTO|SP)-[0-9]+'
        BUGFIX_PATTERN : 'fix[[:space:]]*:[[:space:]]*(APP|KTO|SP)-[0-9]+[[:space:]]+.*#comment[[:space:]]+root[[:space:]]{0,1}cause:[[:space:]]*.{2,}[[:space:]]*\\[[:space:]]*solution[[:space:]]*:[[:space:]]*.{2,}'
    script:    
        - 'branch_name=$(echo "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME")' 
        - >            
            if ! [[ "${branch_name}" =~ "ci" ]] && ! [[ "${branch_name}" =~ $BRANCH_PATTERN ]]; then                
                echo -e "\033[31mBranch name should either be CI related or Jira tickets\033[0;m"
                exit 1
            fi;    
        - >
            if [[ "${branch_name}" =~ $BRANCH_PATTERN ]]; then                
                echo "${CI_COMMIT_MESSAGE}" | npx commitlint
            fi;         
        - |
          ISSUE_DETAIL=$(curl --request GET --url "https://jira.higgstar.com/rest/api/2/issue/${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}" --header "Authorization: Bearer $JIRA_TOKEN" --header "Content-Type: application/json")
          ISSUE_TYPE="$(jq -r .fields.issuetype.name <<< ${ISSUE_DETAIL})"          
          ISSUE_NAME=$(echo "$(jq -r .fields.issuetype.name <<< ${ISSUE_DETAIL})" | tr "[:upper:]" "[:lower:]")
          echo -e "\033[34;1m Jira:$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME, Issue Type: $ISSUE_TYPE , Issue Name: $ISSUE_NAME\033[0;m"    
          RESULT="$($MR_COMMAND)"        
          TITLE=$(echo "$(jq -r .title <<< ${RESULT})" | tr "[:upper:]" "[:lower:]")        
          DESCRIPTION=$(echo "$(jq -r .description <<< ${RESULT})")        
          echo -e "\033[34;1m Merge Request:$TITLE, Description:$DESCRIPTION\033[0;m"
        - >           
            if ! [[ "${TITLE}" =~ "ci" ]] && [[ "${ISSUE_NAME}" =~ "bug" ]] && ! [[ "${DESCRIPTION}" =~ $BUGFIX_PATTERN ]]; then                
                echo -e "\033[31mdescription of fix type should follow pattern as fix:APP-XXX #comment rootcause:xxx \\ solution:xxx\033[0;m"
                exit 1
            fi;
        - >
            if [[ "${ISSUE_TYPE}" =~ "Sub-task" ]]; then                            
                curl --request POST --url "https://jira.higgstar.com/rest/api/2/issue/${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}/transitions" --data '{"transition":{"id":"'${JIRA_SUB_MR_ACTION}'"}}' --header "Authorization: Bearer $JIRA_TOKEN" --header "Content-Type: application/json"
            elif [[ ${ISSUE_TYPE} != null ]]; then
                curl --request POST --url "https://jira.higgstar.com/rest/api/2/issue/${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}/transitions" --data '{"transition":{"id":"'${JIRA_ISSUE_MR_ACTION}'"}}' --header "Authorization: Bearer $JIRA_TOKEN" --header "Content-Type: application/json"
            else
                echo -e "\033[31mIgnore transition for ${ISSUE_TYPE} type\033[0;m"
            fi;
        - pod install --repo-update --allow-root
        - fastlane tests
    artifacts:
        when: always
        paths:
            - "fastlane/test_output/"
        reports:
            junit:
                - "fastlane/test_output/**/*.xml"          
    # - echo "${CI_COMMIT_MESSAGE}" | npx commitlint
