# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
platform :ios do
    before_all do |lane, options|
        unlock_keychain( # Unlock an existing keychain and add it to the keychain search list
            path: "login.keychain-db",
            password: ENV["KEYCHAIN_PASSWORD"]
        )
    end
   
    key_file_path = ENV['API_KEY']
    api_key = app_store_connect_api_key(
            key_id: "76GX29C4YY",#API kid
            issuer_id: "7a9803b0-51d8-44c5-ba26-f916da982cbe",#Issuer ID
            key_filepath: key_file_path,
            duration: 1200, 
            in_house: false, 
        )

	lane :buildIpa  do |options|
	    match(type: "adhoc", readonly: is_ci, app_identifier: "com.kto.asia.dev")
		update_info_plist(plist_path: "ktobet-asia-ios/info.plist", 
				  block: proc do |plist|
					plist["CFBundleVersion"]  = options[:buildVersion]
					plist["CFBundleShortVersionString"] = options[:appVersion]
  				  end)
  		build_app(scheme: "ktobet-asia-ios",
			  workspace: "ktobet-asia-ios.xcworkspace",
            		  include_bitcode: true,
			  clean: true,
		   	  output_directory: "output",
			  export_method: "ad-hoc",
			  skip_package_ipa: true,
			  skip_archive: true
			 )

	end


	lane :buildIpaQat  do |options|
	    match(type: "adhoc", readonly: is_ci, app_identifier:"com.kto.asia.qat-1")
		update_info_plist(plist_path: "ktobet-asia-ios/ktobet-asia-ios-qat-Info.plist", 
				  block: proc do |plist|
					plist["CFBundleVersion"]  = options[:buildVersion]
					plist["CFBundleShortVersionString"] = options[:appVersion]
  				  end)
  		build_app(scheme: "ktobet-asia-ios-qat",
			  workspace: "ktobet-asia-ios.xcworkspace",
            		  include_bitcode: true,
			  clean: true,
		   	  output_directory: "output",
			  export_method: "ad-hoc",
	    		  export_options: { 
					    method: "ad-hoc",
					  }
			 )

	end

	lane :buildIpaStaging  do |options|
	    match(type: "adhoc", readonly: is_ci, app_identifier:"com.kto.asia.stg")
		update_info_plist(plist_path: "ktobet-asia-ios/ktobet-asia-ios-staging-Info.plist", 
				  block: proc do |plist|
					plist["CFBundleVersion"]  = options[:buildVersion]
					plist["CFBundleShortVersionString"] = options[:appVersion]
  				  end)
  		build_app(scheme: "ktobet-asia-ios-staging",
			  workspace: "ktobet-asia-ios.xcworkspace",
            		  include_bitcode: true,
			  clean: true,
		   	  output_directory: "output",
			  export_method: "ad-hoc",
	    		  export_options: { 
					    method: "ad-hoc",
					  }
			 )

	end


	lane :uploadstagingToTestflight do |options|
	match(type: "appstore", readonly: is_ci, app_identifier:"com.kto.asia.stg")
		update_info_plist(plist_path: "ktobet-asia-ios/ktobet-asia-ios-staging-Info.plist", 
				  block: proc do |plist|
					plist["CFBundleVersion"]  = options[:buildVersion]
					plist["CFBundleShortVersionString"] = options[:appVersion]
  				  end)

    		gym(	configuration: "Release",
      		     	scheme: "ktobet-asia-ios-staging",
      		     	clean: true,
      		     	include_bitcode: true,
      			include_symbols: true,
			output_name: "staging-testflight.ipa",
			output_directory: "output",
      			export_method: 'app-store')

    		upload_to_testflight(   username: "higgs-mobile@hotmail.com",
  					app_identifier: "com.kto.asia.stg")
	end



	lane :uploadToTestflight do |options|
	match(type: "appstore", readonly: is_ci, app_identifier:"com.kto.asia.qat-1")
		update_info_plist(plist_path: "ktobet-asia-ios/ktobet-asia-ios-qat-Info.plist", 
				  block: proc do |plist|
					plist["CFBundleVersion"]  = options[:buildVersion]
					plist["CFBundleShortVersionString"] = options[:appVersion]
  				  end)

    		gym(	configuration: "Release",
      		     	scheme: "ktobet-asia-ios-qat",
      		     	clean: true,
      		     	include_bitcode: true,
      			include_symbols: true,
			output_directory: "output",
      			export_method: 'app-store')

    		upload_to_testflight(   username: "higgs-mobile@hotmail.com",
  					app_identifier: "com.kto.asia.qat-1")
	end
	
	lane :buildIpaProduction do |options|
	    match(type: "adhoc", readonly: is_ci, app_identifier:"com.kto.asia")
		update_info_plist(plist_path: "ktobet-asia-ios/ktobet-asia-ios-production-Info.plist", 
				  block: proc do |plist|
                  plist["CFBundleVersion"] = options[:buildVersion]
                  plist["CFBundleShortVersionString"] = options[:appVersion]
  				  end)
  		build_app(scheme: "ktobet-asia-ios-production",
			  workspace: "ktobet-asia-ios.xcworkspace",
              include_bitcode: true,
			  clean: true,
		   	  output_directory: "output",
			  export_method: "ad-hoc",
              export_options: {
                method: "ad-hoc",
              })

	end
 
    lane :buildProdSelf do |options|
        match(type: "appstore", readonly: is_ci, app_identifier:"com.kto.asia.selftest")
        
        update_info_plist(plist_path: "ktobet-asia-ios/ktobet-asia-ios-prod-selftest-Info.plist",
                  block: proc do |plist|
                  plist["CFBundleVersion"] = options[:buildVersion]
                  plist["CFBundleShortVersionString"] = options[:appVersion]
                  end)
                  
        gym(configuration: "Release",
            scheme: "ktobet-asia-ios-prod-selftest",
            clean: true,
            include_bitcode: true,
            include_symbols: true,
            output_directory: "output",
            export_method: 'app-store')

        upload_to_testflight(username: "higgs-mobile@hotmail.com",
            app_identifier: "com.kto.asia.selftest")

    end
    
    lane :buildProdBackup do |options|
        match(type: "appstore", readonly: is_ci, app_identifier:"com.kto.asia.backup")
        
        update_info_plist(plist_path: "ktobet-asia-ios/ktobet-asia-ios-prod-backup-Info.plist",
                  block: proc do |plist|
                  plist["CFBundleVersion"] = options[:buildVersion]
                  plist["CFBundleShortVersionString"] = options[:appVersion]
                  end)
        
        gym(configuration: "Release",
            scheme: "ktobet-asia-ios-prod-backup",
            clean: true,
            include_bitcode: true,
            include_symbols: true,
            output_directory: "output",
            export_method: 'app-store')

        upload_to_testflight(username: "higgs-mobile@hotmail.com",
            app_identifier: "com.kto.asia.backup")

    end
    
    lane :buildQat3 do |options|
        match(type: "appstore", readonly: is_ci, app_identifier:"com.kto.asia.qat3")
        
        update_info_plist(plist_path: "ktobet-asia-ios/ktobet-asia-ios-qat3-Info.plist",
                  block: proc do |plist|
                  plist["CFBundleVersion"] = options[:buildVersion]
                  plist["CFBundleShortVersionString"] = options[:appVersion]
                  end)
        
        gym(configuration: "Release",
            scheme: "ktobet-asia-ios-qat3",
            clean: true,
            include_bitcode: true,
            include_symbols: true,
            output_directory: "output",
            export_method: 'app-store')

        upload_to_testflight(username: "higgs-mobile@hotmail.com",
            app_identifier: "com.kto.asia.qat3")

    end

end
